name: run-tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0, 8.1]
        laravel: [^6.0, ^7.0, ^8.0, ^9.0]
        include:
          - laravel: ^6.0
            testbench: ^4.0
          - laravel: ^7.0
            testbench: ^5.0
          - laravel: ^8.0
            testbench: ^6.0
          - laravel: ^9.0
            testbench: ^7.0
            run-sonarqube-analysis: true
        exclude:
          - php: 7.4
            laravel: ^9.0
          - php: 8.0
            laravel: ^6.0
          - php: 8.1
            laravel: ^6.0
          - php: 8.1
            laravel: ^7.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, pcntl, intl, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench=${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test

      - name: Prepare paths for SonarQube analysis
        if: matrix.run-sonarqube-analysis
        run: |
          sed -i "s|$GITHUB_WORKSPACE|/github/workspace|g" build/logs/clover.xml
          sed -i "s|$GITHUB_WORKSPACE|/github/workspace|g" build/report.junit.xml

      - name: Run SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@master
        if: matrix.run-sonarqube-analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
